language: python
python:
  - "3.4"
install:
  - "pip install -r requirements.txt"
  - "pip install -e ."
before_script:
  - cp goatctf/goatctf/settings.py.example goatctf/goatctf/settings.py
script:
  - cd goatctf/tests
  - py.test
