language: python
python:
  - "3.4"
install:
  - "pip install -r requirements.txt"
  - "pip install -e ."
before_script:
  - sed -e "s/SECRET_KEY = ''/SECRET_KEY = 'test'/" goatctf/goatctf/settings.py.example > goatctf/goatctf/settings.py
  - goatctf/manage.py makemigrations
  - goatctf/manage.py migrate
script:
  - cd goatctf/tests
  - py.test
